export interface VacancyItem {
  id: string;
  title: string;
  category: string;
  categoryEn: string; // Английский субтитр для новой десктопной карточки
  shortDescription: string; // Краткое описание для десктопа (1-2 предложения)
  description: string; // ПОЛНОЕ описание (ОБЯЗАТЕЛЬНО оставляем для мобильной версии)
  requirement: string; // Требования (оставляем для мобильной версии)
  priority: 'КРИТИЧНО' | 'ТЕРМІНОВО' | 'ВІДКРИТО' | 'НАБІР'; // Расширенный список статусов
  span: 'wide' | 'tall' | 'standard'; // ЛЕГАСИ: Обязательно оставляем для мобильного/старого кода
  iconName?: string; // Название иконки Lucide для десктопа
  imageUrl?: string; // Путь к фоновому изображению карточки
}

export interface VacancyCategory {
  id: string;
  categoryName: string;
  icon?: string;
  items: VacancyItem[];
}

export const VACANCIES: VacancyItem[] = [
  /* ── Водії та Техніка ── */
  {
    id: 'v1',
    title: 'Водій',
    category: 'Водії та Техніка',
    categoryEn: 'DRIVERS & MACHINERY',
    requirement: 'Права категорії C/CE, досвід від 2 років',
    shortDescription: 'Безпечне перевезення особового складу та вантажів у зоні бойових дій.',
    description: 'Безпечне перевезення особового складу та вантажів у зоні бойових дій. Технічний контроль транспортного засобу перед виходом на маршрут, дотримання заходів маскування та безпеки.',
    span: 'wide',
    priority: 'ТЕРМІНОВО',
    imageUrl: '/images/vacancies/driver.webp',
    iconName: 'Truck',
  },
  {
    id: 'v2',
    title: 'Водій-електрик',
    category: 'Водії та Техніка',
    categoryEn: 'DRIVERS & MACHINERY',
    requirement: 'Права категорії B/C, базові знання електрики',
    shortDescription: 'Управління транспортним засобом та обслуговування електрообладнання.',
    description: 'Управління транспортним засобом у поєднанні з обслуговуванням електрообладнання підрозділу. Діагностика та усунення несправностей бортової електрики в польових умовах.',
    span: 'standard',
    priority: 'ВІДКРИТО',
    imageUrl: '/images/vacancies/electrican driver.webp',
    iconName: 'Zap',
  },
  {
    id: 'v3',
    title: 'Водій-сапер',
    category: 'Водії та Техніка',
    categoryEn: 'DRIVERS & MACHINERY',
    requirement: 'Права категорії C, підготовка з інженерних справ',
    shortDescription: 'Управління спеціалізованою технікою та участь у розмінуванні.',
    description: 'Управління спеціалізованою технікою інженерних підрозділів, участь у розмінуванні маршрутів і позицій. Знання основ інженерних загороджень та їх подолання.',
    span: 'tall',
    priority: 'КРИТИЧНО',
    imageUrl: '/images/vacancies/Driver  sapper.webp',
    iconName: 'ShieldAlert',
  },
  {
    id: 'v4',
    title: 'Водій-заправник',
    category: 'Водії та Техніка',
    categoryEn: 'DRIVERS & MACHINERY',
    requirement: 'Права категорії C/CE, допуск до ПММ',
    shortDescription: 'Доставка пально-мастильних матеріалів підрозділам.',
    description: 'Доставка пально-мастильних матеріалів підрозділам у складних умовах логістики. Ведення обліку витрат ПММ, дотримання вимог безпеки при роботі з паливом.',
    span: 'standard',
    priority: 'ТЕРМІНОВО',
    imageUrl: '/images/vacancies/gas station driver.webp',
    iconName: 'Fuel',
  },
  {
    id: 'v5',
    title: 'Технік',
    category: 'Водії та Техніка',
    categoryEn: 'DRIVERS & MACHINERY',
    requirement: 'Технічна освіта, досвід ремонту техніки',
    shortDescription: 'Технічне обслуговування та поточний ремонт озброєння і техніки.',
    description: 'Технічне обслуговування та поточний ремонт озброєння, військової техніки й обладнання підрозділу. Контроль технічного стану, складання заявок на запасні частини.',
    span: 'standard',
    priority: 'ВІДКРИТО',
    imageUrl: '/images/vacancies/technician.webp',
    iconName: 'Wrench',
  },
  {
    id: 'v6',
    title: 'Механік',
    category: 'Водії та Техніка',
    categoryEn: 'DRIVERS & MACHINERY',
    requirement: 'Досвід роботи з ДВЗ та гідравлікою',
    shortDescription: 'Польовий ремонт та діагностика двигунів і ходової частини.',
    description: 'Польовий ремонт та діагностика двигунів, ходової частини і агрегатів бойової техніки. Відновлення боєздатності машин у мінімально короткі строки безпосередньо в районі виконання завдань.',
    span: 'standard',
    priority: 'ТЕРМІНОВО',
    imageUrl: '/images/vacancies/mechanic.webp',
    iconName: 'Settings',
  },
  /* ── Медицина ── */
  {
    id: 'v7',
    title: 'Стрілець-санітар',
    category: 'Медицина',
    categoryEn: 'MEDICINE',
    requirement: 'Базовий курс тактичної медицини (ТССС/IFAK)',
    shortDescription: 'Надання домедичної допомоги пораненим під вогнем та евакуація.',
    description: 'Виконання бойових завдань у складі відділення з одночасним наданням домедичної допомоги пораненим під вогнем. Евакуація поранених із зони безпосереднього контакту з противником.',
    span: 'wide',
    priority: 'КРИТИЧНО',
    imageUrl: '/images/vacancies/Sagittarius orderly.webp',
    iconName: 'HeartPulse',
  },
  {
    id: 'v8',
    title: 'Медична сестра',
    category: 'Медицина',
    categoryEn: 'MEDICINE',
    requirement: 'Середня медична освіта, сертифікат медсестри',
    shortDescription: 'Надання кваліфікованої медичної допомоги на медичному пункті.',
    description: 'Надання кваліфікованої медичної допомоги пораненим на медичному пункті підрозділу. Ведення медичної документації, підтримання запасів медикаментів та медичного обладнання.',
    span: 'standard',
    priority: 'ВІДКРИТО',
    imageUrl: '/images/vacancies/nurse.webp',
    iconName: 'Stethoscope',
  },
  {
    id: 'v9',
    title: 'Санітарний інструктор',
    category: 'Медицина',
    categoryEn: 'MEDICINE',
    requirement: 'Медична освіта, досвід роботи з особовим складом',
    shortDescription: 'Організація та проведення занять із тактичної медицини.',
    description: 'Організація та проведення занять із тактичної медицини серед особового складу підрозділу. Контроль укомплектованості аптечок, ведення санітарного стану позицій та транспортних засобів.',
    span: 'standard',
    priority: 'ТЕРМІНОВО',
    imageUrl: '/images/vacancies/sanitary instructor.webp',
    iconName: 'BookOpen',
  },
  /* ── Бойові Спеціальності ── */
  {
    id: 'v10',
    title: 'Навідник',
    category: 'Бойові Спеціальності',
    categoryEn: 'COMBAT SPECIALTIES',
    requirement: 'Досвід роботи з артилерійськими системами',
    shortDescription: 'Наведення та ведення вогню з артилерійських систем.',
    description: 'Наведення та ведення вогню з артилерійських систем за цілями противника згідно з отриманими координатами. Обслуговування озброєння, підготовка боєприпасів, взаємодія з підрозділами коригування.',
    span: 'wide',
    priority: 'КРИТИЧНО',
    imageUrl: '/images/vacancies/spotter.webp',
    iconName: 'Crosshair',
  },
  {
    id: 'v11',
    title: 'Номер обслуги',
    category: 'Бойові Спеціальності',
    categoryEn: 'COMBAT SPECIALTIES',
    requirement: 'Фізична підготовка, базова військова підготовка',
    shortDescription: 'Виконання функцій у складі обслуги зброї чи бойового засобу.',
    description: 'Виконання функцій у складі обслуги зброї чи бойового засобу: підготовка та подача боєприпасів, обслуговування системи, дотримання бойового розпорядку та нормативів.',
    span: 'standard',
    priority: 'ВІДКРИТО',
    imageUrl: '/images/vacancies/service number.webp',
    iconName: 'Swords',
  },
  {
    id: 'v12',
    title: 'Оператор ПТРК',
    category: 'Бойові Спеціальності',
    categoryEn: 'COMBAT SPECIALTIES',
    requirement: 'Технічна підготовка, стресостійкість',
    shortDescription: 'Застосування протитанкових ракетних комплексів.',
    description: 'Застосування протитанкових ракетних комплексів для ураження броньованої техніки та укріплень противника. Технічне обслуговування комплексу, підготовка до бойового застосування у складних умовах рельєфу.',
    span: 'standard',
    priority: 'КРИТИЧНО',
    imageUrl: '/images/vacancies/Combat Specialties.webp',
    iconName: 'Target',
  },
  /* ── Спеціалісти БПЛА/IT ── */
  {
    id: 'v13',
    title: 'Пілот БПЛА',
    category: 'БПЛА / IT',
    categoryEn: 'SPECIALISTS (UAV/IT)',
    requirement: 'Досвід пілотування FPV або мультиротора від 6 міс.',
    shortDescription: 'Пілотування безпілотних літальних апаратів для розвідки та коригування.',
    description: 'Пілотування безпілотних літальних апаратів для ведення повітряної розвідки та коригування артилерійського вогню. Технічне обслуговування дронів, аналіз отриманих даних, взаємодія з бойовими підрозділами.',
    span: 'tall',
    priority: 'КРИТИЧНО',
    imageUrl: '/images/vacancies/UAV operator.webp',
    iconName: 'PlaneTakeoff',
  },
  {
    id: 'v14',
    title: 'Фахівець з IT',
    category: 'БПЛА / IT',
    categoryEn: 'SPECIALISTS (UAV/IT)',
    requirement: 'Досвід у системному адмініструванні або розробці ПЗ',
    shortDescription: 'Технічна підтримка цифрової інфраструктури підрозділу.',
    description: 'Технічна підтримка цифрової інфраструктури підрозділу: налаштування захищеного зв’язку, адміністрування систем управління та забезпечення кіберзахисту операцій.',
    span: 'standard',
    priority: 'ТЕРМІНОВО',
    imageUrl: '/images/vacancies/IT specialist.webp',
    iconName: 'Monitor',
  },
  {
    id: 'v15',
    title: 'Кухар',
    category: 'БПЛА / IT',
    categoryEn: 'SPECIALISTS (UAV/IT)',
    requirement: 'Досвід у сфері приготування їжі, санітарна книжка',
    shortDescription: 'Організація харчування особового складу в польових умовах.',
    description: 'Організація повноцінного гарячого харчування особового складу підрозділу в польових умовах. Планування меню з наявних продуктів, дотримання санітарних норм, раціональне використання продовольчого забезпечення.',
    span: 'standard',
    priority: 'ВІДКРИТО',
    imageUrl: '/images/vacancies/cook.webp',
    iconName: 'Coffee',
  },
  /* ── Адміністрація та Логістика ── */
  {
    id: 'v16',
    title: 'Бухгалтер',
    category: 'Адміністрація',
    categoryEn: 'ADMINISTRATION & LOGISTICS',
    requirement: 'Вища економічна освіта, знання 1С / M.E.Doc',
    shortDescription: 'Ведення фінансово-господарської документації підрозділу.',
    description: 'Ведення фінансово-господарської документації підрозділу, нарахування грошового забезпечення, облік матеріальних цінностей. Підготовка звітності відповідно до вимог Міністерства оборони України.',
    span: 'wide',
    priority: 'ВІДКРИТО',
    imageUrl: '/images/vacancies/accountant.webp',
    iconName: 'Calculator',
  },
]

export const VACANCY_CATEGORIES: VacancyCategory[] = [
  {
    id: 'cat-drivers',
    categoryName: 'Водії та Техніка',
    icon: '/icons/vacancies/driver.svg',
    items: VACANCIES.filter(v => v.category === 'Водії та Техніка'),
  },
  {
    id: 'cat-medicine',
    categoryName: 'Медицина',
    icon: '/icons/vacancies/medic.svg',
    items: VACANCIES.filter(v => v.category === 'Медицина'),
  },
  {
    id: 'cat-combat',
    categoryName: 'Бойові Спеціальності',
    icon: '/icons/vacancies/crosshair.svg',
    items: VACANCIES.filter(v => v.category === 'Бойові Спеціальності'),
  },
  {
    id: 'cat-tech',
    categoryName: 'Спеціалісти (БПЛА/IT)',
    icon: '/icons/vacancies/drone.svg',
    items: VACANCIES.filter(v => v.category === 'БПЛА / IT'),
  },
  {
    id: 'cat-admin',
    categoryName: 'Адміністрація та Логістика',
    icon: '/icons/vacancies/accountant1.svg',
    items: VACANCIES.filter(v => v.category === 'Адміністрація'),
  },
]
